version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ''
    ignore:
      # We support multiple versions of tokio
      - dependency-name: bytes
      - dependency-name: tokio
    labels: []
