# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
yanked = "deny"
git-fetch-with-cli = true
ignore = [
    "RUSTSEC-2021-0124", # tokio 0.2/0.3 (optional deps)
    "RUSTSEC-2023-0005", # tokio 0.2/0.3 (optional deps)
    "RUSTSEC-2021-0072", # tokio 0.3 (optional deps)
]

# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true
build.executables = "deny"
build.interpreted = "deny"
build.include-dependencies = true
build.include-workspace = false # covered by tools/tidy.sh
build.include-archives = true
build.allow-build-scripts = [
    { name = "backtrace" }, # via tokio
    { name = "libc" }, # via backtrace via tokio
    { name = "tokio" }, # 0.3 only
]
build.bypass = [
    { name = "autocfg", allow-globs = ["tests/wrap_ignored"] }, # via tokio 0.3
]

# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
unused-allowed-license = "deny"
private.ignore = true
allow = [
    "Apache-2.0",
    "MIT",
]

# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
]
