# cargo-check-external-types configuration
# https://crates.io/crates/cargo-check-external-types

# The following are external types that are allowed to be exposed in our public API.
allowed_external_types = [
    "futures_core::*",
    "futures_io::*",
    "futures_sink::*",
    "tokio::*",

    # TODO: rustdoc bug
    "pin_project::*",
]
